# Generated by Django 4.2.13 on 2024-07-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('annee_etude', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire_Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.direction')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire_Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.departement')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField()),
                ('contenu', models.FileField(upload_to='rapports/')),
                ('note', models.CharField(max_length=50)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.chef')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.direction'),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField()),
                ('statut', models.CharField(choices=[('EC', 'En cours'), ('RF', 'Refusé'), ('AC', 'Accepté')], default='En cours', max_length=10)),
                ('sujet', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OBS', 'Observation'), ('APP', 'Application'), ('PFE', 'PFE')], default='Observation', max_length=10)),
                ('rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.rh')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
        migrations.AddField(
            model_name='chef',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.departement'),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateField()),
                ('contenu', models.FileField(upload_to='attestation/')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.chef')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
    ]
