# Generated by Django 4.2.13 on 2024-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='mode',
            field=models.CharField(choices=[('hybride', 'Hybride'), ('presentiel', 'Présentiel'), ('adistance', 'À distance')], default='Présentiel', max_length=20),
        ),
    ]
