# Generated by Django 4.2.13 on 2024-07-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_demande_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='rh',
        ),
    ]
