# Generated by Django 4.2.13 on 2024-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_create_rh_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/'),
        ),
    ]
