# Generated by Django 4.2.14 on 2024-07-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_demande_cv_demande_lettre_motivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='responsable_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RespoDepartements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.departement')),
            ],
        ),
    ]
