# Generated by Django 4.2.14 on 2024-07-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_demande_responsable_validated_respodepartements'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='raison_refus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
