# Generated by Django 4.2.14 on 2024-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_demande_raison_refus'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='envoie_responsable',
            field=models.BooleanField(default=False),
        ),
    ]
